const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');menu.focus();}});
const recommendations={doma:['Začněte oblíbeným motivem','Jednorožci, nebo podzimní tvary? Napište, co vás baví, a pro kolik lidí sadu vybíráte. Aktuální motivy a obsah sady společně upřesníme.'],darek:['Vyberte podle obdarovaného','Jaké tvary ho potěší? Do zprávy přidejte oblíbený motiv a datum, kdy dárek potřebujete. Zeptejte se také na obsah a podobu balení.'],skupina:['Nejdřív spočítejte tvořílky','Napište počet lidí, jejich přibližný věk a termín. Domluvte si počet postaviček i to, zda každý potřebuje vlastní barvy a štětec.']};
document.querySelectorAll('input[name="occasion"]').forEach(el=>el.addEventListener('change',()=>{const r=recommendations[el.value];document.querySelector('#rec-title').textContent=r[0];document.querySelector('#rec-text').textContent=r[1];document.querySelector('#rec-link').href='/kontakt/?prilezitost='+encodeURIComponent(el.value);}));
const form=document.querySelector('#inquiry');
if(form){const params=new URLSearchParams(location.search);const o=params.get('prilezitost');if(['doma','darek','skupina','jine'].includes(o))form.elements.prilezitost.value=o;form.elements.motiv.value=(params.get('motiv')||'').slice(0,160);
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d=new FormData(form);const labels={doma:'společné odpoledne',darek:'tvořivý dárek',skupina:'tvoření pro více lidí',jine:'jinou příležitost'};const date=d.get('termin');const parts=['Dobrý den, zajímají mě tvořivé sady Jsem Tvořílek.',d.get('jmeno').trim()?'Jmenuji se '+d.get('jmeno').trim()+'.':'','Hledám '+labels[d.get('prilezitost')]+'.','Motiv: '+d.get('motiv').trim()+'.',d.get('pocet')?'Počet tvořílků: '+d.get('pocet')+'.':'',date?'Potřebuji sadu na '+date.split('-').reverse().join('.')+'.':'',d.get('poznamka').trim(),'Prosím o informace k dostupnosti, obsahu sady, ceně a způsobu předání. Děkuji!'];document.querySelector('#message').value=parts.filter(Boolean).join('\n');document.querySelector('#result').hidden=false;document.querySelector('#copy-status').textContent='Zpráva zatím nebyla odeslána. Zkopírujte ji a vložte do zprávy na Instagramu.';document.querySelector('#message').focus();document.querySelector('#result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});
document.querySelector('#copy').addEventListener('click',async()=>{const t=document.querySelector('#message');try{await navigator.clipboard.writeText(t.value);document.querySelector('#copy-status').textContent='Zkopírováno. Otevřete Instagram a vložte text do zprávy pro @jsem_tvorilek. Zpráva nebyla odeslána.';}catch{t.focus();t.select();document.querySelector('#copy-status').textContent='Automatické kopírování není dostupné. Označený text zkopírujte ručně a vložte do zprávy na Instagramu.';}});}
